TRUNCATE TABLE blob RESTART IDENTITY;
TRUNCATE TABLE path_component RESTART IDENTITY;
TRUNCATE TABLE file RESTART IDENTITY;
TRUNCATE TABLE container RESTART IDENTITY;
ALTER SEQUENCE loose_blob_seq RESTART WITH 1;
