[package]
name = "catfight"
version = "0.1.0"
authors = ["Chris West (Faux) <git@goeswhere.com>"]

[dependencies]
byteorder = "1.0.0"
error-chain = "0.10.0"
peeky-read = "0.1.0"
libc = "0.2.24"

[dev-dependencies]
tempdir = "0.3.5"
tempfile = "2.1.5"
