[package]
authors = ["Chris West (Faux) <git@goeswhere.com>"]
name = "catfight"
version = "0.1.0"

[dependencies]
byteorder = "1"
error-chain = "0.11"
libc = "0.2"
iowrap = "0.1"

[dev-dependencies]
tempdir = "0.3"
tempfile = "2"
