[package]
authors = ["Chris West (Faux) <git@goeswhere.com>"]
name = "deb2pg-reindex"
version = "0.1.0"

[dependencies]
byteorder = "1"
lz4 = "1"
memmap = "0.6"
tempfile = "2"

[dependencies.catfight]
path = "../catfight"

[dependencies.index]
path = "../index"
